ame: Source Orbit Impact Report

on:
  push:
    branches:
      - master

jobs:
  ibmi-build:
    environment: COMMON1
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - run: npm i -g @ibm/sourceorbit
    
      - run: npm i -g @ibm/ibmi-ci

      - name: Generate makefile
        run: so -bf make

      - name: Deploy to IBM i
        run: | 
          ici \
            --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
            --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
            --push "." \
            --cmd "/QOpenSys/pkgs/bin/gmake BIN_LIB=M24CBECK"
        env:
          IBMI_HOST: 'magic.magic-ug.org'
          IBMI_USER: 'M24CBECK'
          IBMI_PASSWORD: 'm24cbeck'
          IBMI_SSH_PORT: 22